instaWeb/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^home/$', views.home, name='home'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

priyagram/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'priyagram.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^instaWeb/', include('instaWeb.urls', namespace="instaWeb")),
    url(r'^$', include('instaWeb.urls', namespace="instaWeb")),
]

instaWeb/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    password = models.CharField(max_length=200)

class Activity(models.Model):
    ACTIVITY_TYPE = (
        ('p', 'Photo'),
        ('l', 'Like'),
        ('c', 'Comment'),
    )
    user_id = models.ForeignKey(User)
    pub_date = models.DateTimeField()
    activity_type = models.CharField(max_length=30,choices=ACTIVITY_TYPE)
    data = models.CharField(max_length=300)

class Photo(models.Model):
    image_url = models.CharField(max_length=300)
    commentCount = models.IntegerField()
    likeCount = models.IntegerField()

instaWeb/views.py
from django.contrib.syndication.views import Feed
from django.core.urlresolvers import reverse
from instaWeb.models import Activity, User, Photo
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse

def index(request):
    return render(request, 'instaWeb/index.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
            if request.user.is_authenticated():
                return HttpResponseRedirect('/instaWeb/home/')
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            return render(request, 'instaWeb/index.html',{'invalid': 'invalid'})

    else:
        return render(request, 'instaWeb/index.html')

def home(request):
    return render(request, 'instaWeb/home.html')

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

instaWeb/templates/instaWeb/home.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title> InstaWeb </title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'instaWeb/style.css' %}" />
</head>
<body>
<header class="top-bar top-bar-new">
    <div  class="top-bar-wrapper">
        <div  class="logo">
            <a  href={% url 'instaWeb:home' %}>Instagram</a>
        </div>
        <div  class="top-bar-left">
            <ul  class="top-bar-actions">
                <li ><a href={% url 'instaWeb:home' %} title="Home" class="link-active top-bar-home"><i></i></a></li>
            </ul>
            <ul class="bluebar-menu-items"></ul>
        </div>
        <div id="top_bar_right" class="top-bar-right account-state">
            <ul class="top-bar-actions">
                <li  class="link-profile">
                    <a  href="javascript:;" id="_dropdownContext0">
                       <strong >{{ user.username }}</strong></a>{% if user.is_authenticated %}<a href="{% url 'instaWeb:logout' %}">Logout</a>{% endif %}<br /><span></span></li></ul></div></div></header>
<div data-reactid=".0.0.2" class="main"><div data-reactid=".0.0.2.0" class="wrapper">
<div class="timelineContainer" data-reactid=".0.0.2.0.0">
    <div class="timelineSidebar" data-reactid=".0.0.2.0.0.0:$media1001318874075064188:0.0">
        <div class="timelineBookmark" data-reactid=".0.0.2.0.0.0:$media1001318874075064188:0.0.0">
        </div>
    </div>
    <div class="timelineCenter" data-reactid=".0.0.2.0.0.0:$media1001318874075064188:0.1">

    </div>
</div>
</div>
</body>
</html>

instaWeb/templates/instaWeb/index.html
<html>
<head>
    <title>priyagram</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'instaWeb/style.css' %}" />
</head>

</html>
<body>
<div class="root">

    <div class="lpDialog">
        <header class="lpDialogHeader" >
            <h1 class="lpLogo">Priyagram</h1>
        </header>
        <div class="lpMain" >
            <div class="Login" >
                {%if invalid %}
                <h3 class="lAlerts" >
                        <span class="lIsErrorAlert">Your username or password was incorrect.</span>
                </h3>
                {%endif%}
                <div class="lMain" >
                    <div class="lFormContainer" >
                        <form id="login_form" method="post" action="/instaWeb/login/">
                             {% csrf_token %}
                            <p class="lfField">
                                <label class="lfFieldLabel" for="lfFieldInputUsername" >Username:</label>
                                <input class="lfFieldInput" id="lfFieldInputUsername" name="username" maxlength="30" autocapitalize="false" autocorrect="false" value="" type="text"></p>
                            <p class="lfField" >
                                <label class="lfFieldLabel" for="lfFieldInputPassword" >Password:</label>
                                <input class="lfFieldInput" id="lfFieldInputPassword" name="password" autocapitalize="false" autocorrect="false" value="" type="password"></p>
                            <p class="lfActions" >
                                <a href="" class="lfForgot" target="_top" >Forgot your password?</a><input class="lfSubmit" value="Log in" type="submit"></p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>